### ISSUE TITLE
self._engine.get_loc(casted_key): KeyError: 'Altitude station m. s. mer'

### ISSUE THREAD

**Issue by laurentgrangier** [Rudd-O/homeassistant-meteoswiss#29]
I get the following error when adding a new MeteoSwiss integration.

```
Logger: aiohttp.server
Source: /usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py:403
First occurred: 14:18:12 (1 occurrences)
Last logged: 14:18:12

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3790, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 152, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 181, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Altitude station m. s. mer'
```

**Comment by Rudd-O** [comment]
That is an issue with https://github.com/websylv/homeassistant-meteoswiss not with this integration.
