### ISSUE TITLE
Fehler in Log seit Update vom 13.2

### ISSUE THREAD

**Issue by 7R0J4Ner** [Rudd-O/homeassistant-meteoswiss#7]
Hallo Rudd-O

Erstmal genial, das du diese Erweiterung weiter unterhälst, besten Dank dafür!

Seit dem update von heute Abend habe ich jedoch folgende fehler in meinem Log:

Logger: homeassistant.setup
Source: setup.py:343
First occurred: 19:46:57 (1 occurrences)
Last logged: 19:46:57

Unable to prepare setup for platform meteo-swiss.weather: Platform not found (Exception importing custom_components.meteo-swiss.weather).

Logger: homeassistant.loader
Source: loader.py:766
First occurred: 20:27:37 (1 occurrences)
Last logged: 20:27:37

Unexpected exception importing platform custom_components.meteo-swiss.weather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 749, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 766, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/meteo-swiss/weather.py", line 187
    "https://rudd-o.com/meteostations,
    ^
SyntaxError: unterminated string literal (detected at line 187)

**Comment by Rudd-O** [comment]
I will probably begin adding tests to prevent these errors from taking place in the future.
